package yalearts;

import javafx.geometry.Pos;
import javafx.scene.control.Button;
import javafx.scene.control.Hyperlink;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.scene.text.TextFlow;

public class About {
    Text pageTitle;
    Text body1Title;
    Text body1;
    Text body2Title;
    Text body2;
    Text body3Title;
    Text body3;

   

    HBox hb0 = new HBox();
    HBox hb1 = new HBox();
    HBox hb2 = new HBox();
    HBox hb3 = new HBox();

    VBox vbContent = new VBox();

    GridPane linkPane = new GridPane();

  
    
    public About(VBox vb) {
        pageTitle = new Text("About The School");
        body1Title = new Text("The Yale School of Art is a graduate school that confers Master of Fine Arts Degrees in Graphic Design, Painting/Printmaking, Photography, and Sculpture");
        body1 = new Text("Artists and designers of unusual promise and strong motivation are provided an educational context in which they can explore the potential of their own talents in the midst of an intense critical dialogue. This dialogue is generated by their peers, by distinguished visitors, and by a faculty comprised of professional artists of acknowledged accomplishment.The graduate students primary educational experience at Yale is centered on the students own studio activity. Supporting this enterprise are the experience, knowledge, and skills gained from rigorous, structured courses such as drawing, filmmaking, the relativity of color, and the rich academic offerings found throughout Yale. Each student is routinely exposed to many aesthetic positions through encounters with faculty members and visitors. The School is devoted not only to the refinement of visual skills, but also to the cultivation of the mind. Students must bring creative force and imagination to their own development, for these qualities cannot be taught—they can only be stimulated and appreciated.The School of Art offers an undergraduate art major for students in Yale College (see the bulletin Yale College Programs of Study). In addition, the Schools courses are open to students in the Graduate School of Arts and Sciences and other professional schools of the University, and School of Art students may enroll in elective courses in the Graduate School and other professional schools as well as in the College with permission.");
        body2Title = new Text("Master of Fine Arts Degree (MFAs)");
        body2 = new Text("The degree of Master of Fine Arts is the only degree offered by the School of Art. It is conferred by the University upon recommendation of the faculty after successful completion of all course work in residence and after a thesis presentation that has been approved by the faculty. It implies distinctive achievement on the part of students in studies in the professional area of their choice and demonstrated capacity for independent work. The minimum residence requirement is two years. All candidates’ work is reviewed by faculty at the end of each term. If the work is not considered satisfactory, the student may not be invited back to complete the program (see section on Review and Awards under Academic Regulations in the chapter General Information). All degree candidates are expected to be present at the Commencement exercises in May unless excused by the dean.Course work for the Master of Fine Arts degree carries a minimum of sixty credits. The disposition of these credits varies according to the area of study and is agreed upon at the time of registration between the student and the student’s faculty adviser.");
        body3Title = new Text("Public Lectures and Exhibitions");
        body3 = new Text("Each department has its own visitors program in which professionals from outside the School are invited to lecture to students or take part in critiques.The School also facilitates a public all-school lecture program, in which ideas of general and cross-disciplinary importance are explored by visiting artists and members of the faculty in events typically hosted in the evening that are free and open to the public.The School of Art’s galleries in Green Hall and EIK at 32 Edgewood Avenue provide a year-round forum for the exhibition of work by students, faculty, and special guests in the four graduate departments of the School and the undergraduate program. Green Gallery is open to the public when exhibitions are scheduled, but open hours vary by semester. EIK is open during limited hours for specific exhibitions and events. Please refer to the Gallery & Publications page for more information.");


        Button missionStatement = new Button("Mission Statement");
        missionStatement.setOnAction(e -> {
            // reveal text 
        });

         Button landAck = new Button("Land Acknowledgment");
        landAck.setOnAction(e -> {
            // reveal text  
        });

         Button diversity = new Button("Diversity");
        diversity.setOnAction(e -> {
            // reveal text
        });

         Button incl = new Button("Inclusion & Belonging");
        incl.setOnAction(e -> {
            // reveal text
        });

         Button studyAreas = new Button("Study Areas");
        studyAreas.setOnAction(e -> {
            // reveal text
        });

         Button people = new Button("People");
        people.setOnAction(e -> {
            // reveal text
        });

         Button resources = new Button("Resources for Faculty & Students");
        resources.setOnAction(e -> {
            // reveal text
        });

         Button visiting = new Button("Visiting");
        visiting.setOnAction(e -> {
            // reveal text
        });

         Button facilities = new Button("Facilities");
        facilities.setOnAction(e -> {
            // reveal text
        });

         Button support = new Button("Support The School");
        support.setOnAction(e -> {
            // support
        });

         Button contact = new Button("Contact");
        contact.setOnAction(e -> {
            // reveal text
        });

          Button history = new Button("History");
            history.setOnAction(e -> {
            // reveal text
            });
        
             Button thisSite = new Button("About This Site");
            thisSite.setOnAction(e -> {
            // reveal text
            });
        
        linkPane.getChildren().addAll(missionStatement,landAck,diversity,incl,studyAreas,people,resources,visiting,facilities,support,contact,history,thisSite);
          
        hb0.getChildren().addAll( pageTitle);
        
        hb1.getChildren().addAll(body1Title,body1);
        
        hb2.getChildren().addAll(body2Title,body2);
        
        hb3.getChildren().addAll(body3Title, body3);
        
        vbContent.getChildren().addAll(hb0, hb1, hb2, hb3,linkPane);
          
        vbContent.setAlignment(Pos.CENTER);

        vb.getChildren().add(vbContent);
        

    }
    
   
}
